const WIDTH = 600;
const HEIGHT = 200;
const PADDING = 40;

export const conf = {
  WIDTH: WIDTH,
  HEIGHT: HEIGHT,
  DPI_WIDTH: WIDTH * 2,
  DPI_HEIGHT: HEIGHT * 2,
  ROWS_COUNT: 5,
  PADDING: PADDING,
  VIEW_HEIGHT: HEIGHT * 2 - PADDING * 2,
};
